name: udemy_clone_responsivo
description: Clone Udemy Responsivo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.1.0
  auto_size_text: ^3.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
